/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    Api: {
      type: "sst.aws.ApiGatewayV2";
      url: string;
    };
    Assets: {
      name: string;
      type: "sst.aws.Bucket";
    };
    BetterAuthSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    Client: {
      type: "sst.aws.StaticSite";
      url: string;
    };
    DatabaseUrl: {
      type: "sst.sst.Secret";
      value: string;
    };
    ImagePaletteDeadLetterQueue: {
      type: "sst.aws.Queue";
      url: string;
    };
    ImagePipelineCallbackSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    ImagePaletteQueue: {
      type: "sst.aws.Queue";
      url: string;
    };
    ImageVariantsDeadLetterQueue: {
      type: "sst.aws.Queue";
      url: string;
    };
    ImageVariantsQueue: {
      type: "sst.aws.Queue";
      url: string;
    };
    ResendApiKey: {
      type: "sst.sst.Secret";
      value: string;
    };
  }
}

import "sst";
export {};
